### PR TITLE
socket io join user and new session

### LINKED ISSUE #94: Implement Socket.io for creating new session and user join
As a user I would like to see added sessions in real time to then join them.

### PR DESCRIPTION
**Pull request by SteffenBerlin**
resolves #94

### CODE REVIEW

**Comment by jake-shasteen** [comment]
Hello!

Some things I notice as I'm playing around with this build:
- The 'create a new group' field defaults to null in /sessions and should probably just have the 'name' placeholder. (fixed as of 5:56pm )
- Nice job getting sessions set up! When I log in with a window in Chrome and a window in Safari as different users, I can join the session and it pops up in the other window in real time.
- However, if I leave the room with one window and come back, it doesn't take me out of the list so I end up with multiples of the same user in the list.

Really great work guys! Things are coming together!

**Comment by jake-shasteen** [comment]
Some stuff I found out during more testing:

When I sign up but I am already logged in as a different user, I stay logged in as the original user

It should add name when someone else joins ( yes! does this! )
It should remove a name from the dom and database when someone disconnects or leaves or hits the back button in their browser ( does not yet do this )
It should not add names to other rooms -- just the one that was joined ( it does this! )
Should remove a session from the list when the last person disconnects or leaves or hits the back button in their browser ( does not do this )
Should not let someone join more than one session ( does not do this, would probably be resolved by removing people when they disconnect )

**Comment by kathy-ems** [comment]
- There is a function, broadcastSession, that has nothing inside it. It's not called anywhere. (rm 6pm 24 feb -- jake )
- In client/app/sessions/joinsessions.html, the on-click has 3+ functions called with one on-click. This probably works fine, though my gut wonders if having only one function per on-click is a better practice. I'm open to hear your reasoning for having more than one function call on an on-click.
  (refactor 6:10pm -- jake )
- Remove the console log from line 10 of client/app/sessions/sessions.js and unnecessary comments like //$scope.user.name = "Julie"; (rm 6:10pm --jake )
- in client/app/sessions/sessions.js, line 25, can $scope.sessionName = Session.getSession(); be removed? There is no reference to the current user's session on this page. (fixed)
- in Services.js line 48, has location and line 72 has $location, should one of these be changed?
  ( refactored 6:26 --jake )
- There is a console log on 51 and 52 on  server/sessions_users/sessions_usersController.js (fixed)

**Comment by jake-shasteen** [comment]
I am taking on the requested fixes

**Pull request merged**
