### PR TITLE
Builds out chai tests

### LINKED ISSUE #90: Set up Mocha, Chai (server)
Server side

### PR DESCRIPTION
**Pull request by kathy-ems**
closes #90

### CODE REVIEW

**Comment by kathy-ems** [comment]
http://www.sitepoint.com/unit-test-javascript-mocha-chai/

You'll have to `npm install` and ~~`npm install -g mocha`~~ `grunt mocha` to run server side tests otherwise you can run it in the browser with the testrunner.html file

**Comment by jake-shasteen** [comment]
reviewing this

**Comment by jake-shasteen** [comment]
Could not get the branch to work until I did 'npm install grunt' after the normal npm install. Can you add grunt (just normal grunt) to the package.json?

Everything else looks good and works! Thanks for building out the testing skeleton!

**Comment by kathy-ems** [comment]
Added grunt to package.json

**Pull request merged**
